create schema if not exists "spring_app";
set search_path to "spring_app";

create table person
(
    id      int generated by default as identity primary key,
    name    varchar(30) not null,
    age     int         not null check ( age >= 0 ),
    email   varchar(90) not null unique,
    address varchar(255)
);